[package]
name = "onernote"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
packed_struct = "0.10.1"
uuid = "1.4.1"
